Repository SystemCrafters/wiki-site, pull requests merged in 2021-06, with the labels that each got.

#3 Add information about various browsers
  content/guix/browsers.org
Labels: article, enhancement

#8 WIP: Overhaul UX
  content/community/code-of-conduct.org
  content/community/getting-involved.org
  content/index.org
  publish.el
Labels: enhancement

#17 Add nvidia information
  content/guix/nvidia.org
Labels: article
